version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    docker:
      - image: cimg/node:15.4.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run: npm run test:vue3

      - codecov/upload:
          file: './coverage/coverage-final.json'
          flags: 'vue3'

      - run: npm run test:vue2

      - codecov/upload:
          file: './coverage/coverage-final.json'
          flags: 'vue2'